server:
  port: 8601
spring:
  application:
    name: wy-admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

